# -*- coding: utf-8 -*-
"""prob2_NLU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yEzh9WaK-ap08LQVWYSWgPpVRxYKnnYw
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import random

##load dataset and preprocess names
with open('TrainingNames.txt', 'r') as f:
    names = [line.strip().lower() for line in f.readlines() if line.strip()]

all_chars = sorted(list(set(''.join(names)))) + ['<SOS>', '<EOS>']
n_chars = len(all_chars)
char_to_idx = {char: i for i, char in enumerate(all_chars)}
idx_to_char = {i: char for i, char in enumerate(all_chars)}

##print model hyperparameters
def print_hyperparameters(model_name, hidden_size, embedding_size, lr, epochs):
    print(f"\n--- {model_name} Hyperparameters ---")
    print(f"Hidden Size     : {hidden_size}")
    print(f"Embedding Size  : {embedding_size}")
    print(f"Learning Rate   : {lr}")
    print(f"Epochs          : {epochs}")

##vanilla rnn
class VanillaRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(VanillaRNN, self).__init__()
        self.hidden_size = hidden_size

        self.embedding = nn.Embedding(input_size, 64)

        self.Wxh = nn.Parameter(torch.randn(64, hidden_size) * 0.01)
        self.Whh = nn.Parameter(torch.randn(hidden_size, hidden_size) * 0.01)
        self.bh = nn.Parameter(torch.zeros(hidden_size))

        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x, hidden):
        x = self.embedding(x)

        outputs = []
        h = hidden.squeeze(0)

        for t in range(x.size(1)):
            xt = x[:, t, :]
            h = torch.tanh(xt @ self.Wxh + h @ self.Whh + self.bh)
            outputs.append(h.unsqueeze(1))

        outputs = torch.cat(outputs, dim=1)
        return self.fc(outputs), h.unsqueeze(0)

    def init_hidden(self, batch_size=1):
        return torch.zeros(1, 1, self.hidden_size)

class BLSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(BLSTMModel, self).__init__()
        self.hidden_size = hidden_size
        self.embedding = nn.Embedding(input_size, 64, padding_idx=0)
        self.lstm = nn.LSTM(64, hidden_size, bidirectional=True, batch_first=True)
        self.fc = nn.Linear(hidden_size * 2, output_size)

    def forward(self, x, hidden=None):
        # embeds: (batch, seq_len, 64)
        embeds = self.embedding(x)

        out, (h_n, c_n) = self.lstm(embeds, hidden)

        h_n_concat = torch.cat((h_n[0:1], h_n[1:2]), dim=2) # Result: (1, batch, 256)
        c_n_concat = torch.cat((c_n[0:1], c_n[1:2]), dim=2)

        return self.fc(out), (h_n_concat, c_n_concat)

    def init_hidden(self, batch_size=1):
        return (torch.zeros(2, batch_size, self.hidden_size),
                torch.zeros(2, batch_size, self.hidden_size))


##rnn with causal attention mechanism over previous hidden states
class AttentionRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(AttentionRNN, self).__init__()
        self.hidden_size = hidden_size

        self.embedding = nn.Embedding(input_size, 64)

        self.Wxh = nn.Linear(64, hidden_size)
        self.Whh = nn.Linear(hidden_size, hidden_size)

        self.attn_linear = nn.Linear(hidden_size, hidden_size)
        self.v = nn.Linear(hidden_size, 1, bias=False)

        self.fc = nn.Linear(hidden_size * 2, output_size)

    def forward(self, x, hidden):
        embeddings = self.embedding(x)
        seq_len = x.size(1)
        h = hidden.squeeze(0)

        all_h = []

        for t in range(seq_len):
            xt = embeddings[:, t, :]
            h = torch.tanh(self.Wxh(xt) + self.Whh(h))
            all_h.append(h.unsqueeze(1))

        all_h = torch.cat(all_h, dim=1)

        outputs = []

        for t in range(seq_len):
            query = all_h[:, t:t+1, :]
            keys = all_h[:, :t+1, :]

            energy = torch.tanh(self.attn_linear(query + keys))
            weights = F.softmax(self.v(energy), dim=1)

            context = torch.sum(weights * keys, dim=1)

            combined = torch.cat((all_h[:, t, :], context), dim=1)
            outputs.append(self.fc(combined).unsqueeze(1))

        out = torch.cat(outputs, dim=1)
        return out, h.unsqueeze(0)

    def init_hidden(self, batch_size=1):
        return torch.zeros(1, 1, self.hidden_size)

##print architecture details including parameter shapes
def print_architecture_details(model_name, model):
    print(f"\n{'='*20} {model_name.upper()} ARCHITECTURE {'='*20}")
    for name, param in model.named_parameters():
        print(f"{name:<25} | Shape: {tuple(param.shape)}")
    print(f"{'-'*70}")

    if hasattr(model, 'embedding'):
        print(f"Embedding Layer: vocab_size={model.embedding.num_embeddings}, embed_dim={model.embedding.embedding_dim}")
    if hasattr(model, 'hidden_size'):
        print(f"Hidden Size: {model.hidden_size}")
    if hasattr(model, 'fc'):
        print(f"Fully Connected Layer: in_features={model.fc.in_features}, out_features={model.fc.out_features}")

    print(f"{'='*70}\n")

##count total trainable parameters in model
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

##training loop
def train_model(model, model_name, epochs=50):
    optimizer = torch.optim.Adam(model.parameters(), lr=0.005)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        total_loss = 0
        random.shuffle(names)

        for name in names:
            model.zero_grad()
            hidden = model.init_hidden(batch_size=1)

            input_indices = [char_to_idx['<SOS>']] + [char_to_idx[c] for c in name]
            target_indices = [char_to_idx[c] for c in name] + [char_to_idx['<EOS>']]

            input_tensor = torch.tensor(input_indices).unsqueeze(0)
            target_tensor = torch.tensor(target_indices)

            output, _ = model(input_tensor, hidden)

            loss = criterion(output.squeeze(0), target_tensor)

            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        ##log metrics every 10 epochs
        if (epoch + 1) % 10 == 0:
            avg_loss = total_loss / len(names)
            novelty, diversity, samples = evaluate_metrics(model, names)

            print(f"\n[{model_name}] Epoch {epoch+1}")
            print(f"Avg Loss   : {avg_loss:.4f}")
            print(f"Novelty    : {novelty:.2f}")
            print(f"Diversity  : {diversity:.2f}")

            ##print sample generated names
            print("Sample Names:")
            for s in samples:
                print(f" - {s}")


def generate_name(model, max_length=15):
    model.eval()
    with torch.no_grad():
        hidden = model.init_hidden(batch_size=1)
        input_idx = torch.tensor([[char_to_idx['<SOS>']]])
        generated_chars = []

        for _ in range(max_length):
            output, _ = model(input_idx, hidden)

            probs = torch.softmax(output[0, -1], dim=0)
            top_i = torch.multinomial(probs, 1).item()

            char = idx_to_char[top_i]

            if char == '<EOS>':
                break

            generated_chars.append(char)

            input_indices = [char_to_idx['<SOS>']] + [char_to_idx[c] for c in generated_chars]
            input_idx = torch.tensor(input_indices).unsqueeze(0)

            hidden = model.init_hidden(batch_size=1)

        return "".join(generated_chars)

def evaluate_metrics(model, training_names, n_samples=200):
    generated = [generate_name(model) for _ in range(n_samples)]
    unique_generated = set(generated)

    diversity = len(unique_generated) / n_samples

    novel_names = [n for n in unique_generated if n not in training_names]
    novelty_rate = len(novel_names) / len(unique_generated) if unique_generated else 0

    return novelty_rate, diversity, list(unique_generated)[:5]

##initialize all models
models = {
    "Vanilla RNN": VanillaRNN(n_chars, 128, n_chars),
    "BLSTM": BLSTMModel(n_chars, 128, n_chars),
    "Attention RNN": AttentionRNN(n_chars, 128, n_chars)
}

results = []

##train each model and collect evaluation metrics
for name, m in models.items():
    print_architecture_details(name, m)
    print_hyperparameters(name, 128, 64, 0.005, 50)

    train_model(m, name)

    novelty, diversity, samples = evaluate_metrics(m, names)
    params = count_parameters(m)

    results.append((name, params, novelty, diversity, samples))

print("\n" + "="*70)
print("FINAL MODEL COMPARISON")
print("="*70)

print(f"{'Model':<20} | {'Params':<10} | {'Novelty':<10} | {'Diversity':<10}")
print("-"*70)

##print comparison table
for r in results:
    name, params, novelty, diversity, _ = r
    print(f"{name:<20} | {params:<10} | {novelty:<10.2f} | {diversity:<10.2f}")

print("="*70)

print("\nSAMPLE GENERATED NAMES PER MODEL")
print("="*70)

for r in results:
    name, _, _, _, samples = r
    print(f"\n{name}:")
    for s in samples:
        print(f" - {s}")

